# ===================================================================
# CONFIGURACIÓN DEL SERVIDOR
# ===================================================================
server.port=8080
server.servlet.context-path=/api

# ===================================================================
# CONFIGURACIÓN DE CONEXIÓN A ORACLE DB
# ===================================================================
# Usamos el Service Name XEPDB1 que es la base de datos pluggable por defecto en Oracle XE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=botica
spring.datasource.password=123456789
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Pool de conexiones (HikariCP viene por defecto, lo optimizamos para desarrollo)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# Dialecto moderno de Oracle indispensable para que Hibernate entienda las columnas IDENTITY
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 'validate' es el modo ideal para desarrollo cuando ya creaste la tabla a mano en SQL.
# Verifica que tu entidad Java coincida exactamente con las columnas de Oracle.
spring.jpa.hibernate.ddl-auto=validate

# Muestra y formatea las consultas SQL reales en la consola de Java para hacer debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ===================================================================
# OPTIMIZACIÓN EXCLUSIVA PARA JAVA 21
# ===================================================================
# Activamos el uso de Hilos Virtuales (Virtual Threads) para un rendimiento brutal
spring.threads.virtual.enabled=true

app.cors.allowed-origin=${ALLOWED_ORIGIN:http://localhost:4200}

app.jwt.secret=${JWT_SECRET_KEY}